create table public."CryptoInvoices" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  "productName" text null,
  price real null,
  "requestNetworkID" text null,
  "requestNetworkPaymentReference" text null,
  "paymentStatus" text null,
  "transactionHash" text null,
  "paymentCurrency" text null,
  "paymentNetwork" text null,
  constraint CryptoInvoices_pkey primary key (id),
  constraint CryptoInvoices_requestNetworkID_key unique ("requestNetworkID"),
  constraint CryptoInvoices_requestNetworkPaymentReference_key unique ("requestNetworkPaymentReference"),
  constraint CryptoInvoices_transactionHash_key unique ("transactionHash")
) TABLESPACE pg_default;