create table public."ProductsTest" (
  id bigint generated by default as identity not null,
  "productName" text null,
  price real null,
  constraint ProductsTest_pkey primary key (id)
) TABLESPACE pg_default;